spring:
  application:
    name: auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0
  datasource:
    url: jdbc:postgresql://postgres_db:5432/dev-db
    username: dev-user
    password: dev-psw
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /auth/api/v1

teamsync:
  security:
    internal-jwt-filter:
      skip-path-prefixes:
        - /auth/api/v1/entra
    jwt:
      base64key: ${JWT_KEY}
      expiration-time-ms: 3600000 # 1 hour
      issuer: teamsync
      user-id-claim: user_id
    web:
      cors-allowed-origins:
        - http://localhost:5173
        - http://localhost:8000
  client:
    resume:
      api-url: http://localhost/resume/api/v1

logging:
  level:
    org.springframework.security: DEBUG
  file:
    max-history: 3
    max-size: 10MB
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB