spring:
  application:
    name: auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0
  datasource:
    url: ${DB_MAIN_JDBC}
    username: ${DB_MAIN_USER}
    password: ${DB_MAIN_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /auth/api/v1

teamsync:
  security:
    internal-jwt-filter:
      skip-path-prefixes:
        - /auth/api/v1/entra
    jwt:
      base64key: ${JWT_KEY}
      expiration-time-ms: 3600000 # 1 hour
      issuer: teamsync
      user-id-claim: user_id
    web:
      cors-allowed-origins:
        - http://localhost:5173
        - http://localhost:8000
        - https://shqcore.ru
        - https://dev.shqcore.ru
        - https://team-sync.online
        - https://dev.team-sync.online

  client:
    resume:
      api-url: ${RESUME_HOST}

logging:
  level:
    org.springframework.security: DEBUG