spring:
  application:
    name: auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/TENANT_ID/v2.0
  web:
    allowed-origins: http://localhost:5173