version: '3.8'

services:

  backend-auth:
    build: ./back/auth
    ports: 
      - "8084:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - TENANT_ID=8b33a0fd-354e-48f9-b6fa-b85f0b6e3e55
      - JWT_KEY=c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0
    depends_on:
      - postgres

  backend-resume:
    build: ./back/resume
    ports:
      - "8085:8080"
    volumes:
      - ./logs:/app/logs
    environment:
      - TENANT_ID=8b33a0fd-354e-48f9-b6fa-b85f0b6e3e55
      - JWT_KEY=c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0
    depends_on:
      - postgres
  
  backend-projects:
    build: ./back/projects
    environment:
      - TENANT_ID=8b33a0fd-354e-48f9-b6fa-b85f0b6e3e55
      - JWT_KEY=c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0
    ports: 
      - "8081:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres

  backend-recommendation:
    build: ./back/recommendation
    volumes:
      - ./logs:/app/logs
    ports: 
      - "8082:8080"
      - "8083:9090"
      
  frontend:
    build: ./front
  
  ml-recsys:
    build: ./ml/recsys-service
    ports: 
      - "8000:8000"
  
  ml-search:
    build: ./ml/search-service
    ports: 
      - "8001:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend-projects
      - backend-auth

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dev-db
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-psw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.4.0
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  liquibase:
    image: liquibase/liquibase:4.32.0
    container_name: liquibase
    volumes:
      - ./migration:/migration
    working_dir: /migration
    depends_on:
      - postgres
    command: >
      --defaultsFile=liquibase.properties
      update

  keydb:
    image: bitnami/keydb:6.3.4
    container_name: keydb
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
    environment:
      - KEYDB_PASSWORD=dev-keydb-psw
    restart: unless-stopped

  airflow-postgres:
    image: postgres:16
    container_name: airflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: airflow-db
      POSTGRES_USER: airflow-user
      POSTGRES_PASSWORD: airflow-psw
    ports:
      - "5433:5432"
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data

  airflow-log-init:
    image: busybox
    command: sh -c "mkdir -p /opt/airflow/logs/scheduler && chmod -R 777 /opt/airflow/logs"
    volumes:
      - ./airflow/logs:/opt/airflow/logs

  airflow-init:
    image: apache/airflow:2.9.0
    container_name: airflow_init
    depends_on:
      - airflow-postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow-user:airflow-psw@airflow-postgres/airflow-db
    command: db init
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow_scheduler
    restart: unless-stopped
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow-user:airflow-psw@airflow-postgres/airflow-db
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - airflow-postgres
      - airflow-init
      - airflow-log-init

volumes:
  pgdata:
  pgadmin_data:
  keydb_data:
  airflow_pgdata:
    
