version: '3.8'

services:
  backend-auth-dev:
    image: ssspamqe/ts-auth:${TS_AUTH_TAG}
    ports: 
      - "9000:8080"
    env_file:
      - .env
    depends_on:
      - postgres-dev
      - liquibase-dev
  
  backend-projects-dev:
    image: ssspamqe/ts-projects:${TS_PROJECTS_TAG}
    env_file:
      - .env
    ports: 
      - "9001:8080"
    depends_on:
      - postgres-dev
      - liquibase-dev
      
  backend-resume-dev:
    image: ssspamqe/ts-resume:${TS_RESUME_TAG}
    env_file:
      - .env
    ports: 
      - "9002:8080"
    depends_on:
      - postgres-dev
      - liquibase-dev

  frontend-dev:
    image: ssspamqe/ts-frontend-dev:${TS_FRONTEND_TAG}
    ports: 
      - "9004:80"

  postgres-dev:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "9006:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

  pgadmin-dev:
    image: dpage/pgadmin4:9.4.0
    restart: unless-stopped
    ports:
      - "9007:80"
    volumes:
      - pgadmin_data-dev:/var/lib/pgadmin
    depends_on:
      - postgres-dev

  liquibase-dev:
    image: liquibase/liquibase:4.32.0
    volumes:
      - ./migration:/migration
    working_dir: /migration
    depends_on:
      - postgres-dev
    command: >
      --changeLogFile=changelog/changelog.yml
      --url=${DB_MAIN_JDBC}
      --username=${DB_MAIN_USER}
      --password=${DB_MAIN_PASSWORD}
      --driver=org.postgresql.Driver
      --logLevel=info
      update

volumes:
  pgdata-dev:
  pgadmin_data-dev: