version: '3.8'

services:
  backend-auth:
    build: ./back/auth
    ports: 
      - "8084:8080"
    environment:
      - TENANT_ID=${TENANT_ID}
      - JWT_KEY=${JWT_KEY}
      - DB_MAIN_JDBC=jdbc:postgresql://postgres:5432/${DB_NAME}
      - DB_MAIN_USER=${DB_USER}
      - DB_MAIN_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
      - liquibase

  backend-projects:
    build: ./back/projects
    environment:
      - TENANT_ID=${TENANT_ID}
      - JWT_KEY=${JWT_KEY}
      - DB_MAIN_JDBC=jdbc:postgresql://postgres:5432/${DB_NAME}
      - DB_MAIN_USER=${DB_USER}
      - DB_MAIN_PASSWORD=${DB_PASSWORD}
    ports: 
      - "8081:8080"
    depends_on:
      - postgres
      - liquibase
      
  frontend:
    build: ./front
    ports: 
      - "3000:80"
    depends_on:
      - backend-auth
      - backend-projects

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.4.0
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  liquibase:
    image: liquibase/liquibase:4.32.0
    volumes:
      - ./migration:/migration
    working_dir: /migration
    depends_on:
      - postgres
    command: >
      --changeLogFile=changelog/changelog.yml
      --url=jdbc:postgresql://postgres:5432/${DB_NAME}
      --username=${DB_USER}
      --password=${DB_PASSWORD}
      --driver=org.postgresql.Driver
      --logLevel=info
      update

volumes:
  pgdata:
  pgadmin_data: