spring:
  application:
    name: projects

  datasource:
    url: ${DB_MAIN_JDBC}
    username: ${DB_MAIN_USER}
    password: ${DB_MAIN_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /projects/api/v1

teamsync:
  security:
    jwt:
      base64key: ${JWT_KEY}
      expiration-time-ms: 3600000 # 1 hour
      issuer: teamsync
      user-id-claim: user_id
    web:
      cors-allowed-origins:
        - http://localhost:5173
        - http://localhost:8000
        - https://shqcore.ru
        - https://dev.shqcore.ru
        - https://team-sync.online
        - https://dev.team-sync.online
  pagination:
    default:
      page-number: 0
      page-size: 100

logging:
  level:
    org.springframework.security: DEBUG