spring:
  application:
    name: projects

  datasource:
    url: jdbc:postgresql://localhost:5432/dev-db
    username: dev-user
    password: dev-psw
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    context-path: /projects/api/v1

teamsync:
  security:
    jwt:
      base64key: ${JWT_KEY}
      expiration-time-ms: 3600000 # 1 hour
      issuer: teamsync
      user-id-claim: user_id


logging:
  level:
    org.springframework.security: DEBUG