spring:
  application:
    name: resume

  datasource:
    url: jdbc:postgresql://postgres_db:5432/dev-db
    username: dev-user
    password: dev-psw
server:
  port: 8080
  servlet:
    context-path: /resume/api/v1
