spring:
  application:
    name: resume

  datasource:
    url: ${DB_MAIN_JDBC}
    username: ${DB_MAIN_USER}
    password: ${DB_MAIN_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /resume/api/v1

logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
    ru.teamsync.resume: INFO

teamsync:
  security:
    jwt:
      base64key: ${JWT_KEY}
      expiration-time-ms: 3600000 # 1 hour
      issuer: teamsync
      user-id-claim: user_id
    web:
      cors-allowed-origins:
        - http://localhost:5173
        - http://localhost:8000
        - https://shqcore.ru
        - https://dev.shqcore.ru
        - https://team-sync.online
        - https://dev.team-sync.online
  client:
    embedder:
      api-url: ${EMBEDDER_HOST}
