spring:
  application:
    name: resume

  datasource:
    url: jdbc:postgresql://postgres_db:5432/dev-db
    username: dev-user
    password: dev-psw
  
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /resume/api/v1

logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
    ru.teamsync.resume: INFO

teamsync:
  security:
    jwt:
      base64key: c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0
      expiration-time-ms: 3600000 # 1 hour
      issuer: teamsync
      user-id-claim: user_id