openapi: 3.0.3
info:
  title: Resume Service API
  description: API for managing user (student/professor) profile
  version: 1.0.0

servers:
  - url: http://localhost

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    BaseResponse:
      type: object
      properties:
        error:
          type: object
          nullable: true
          properties:
            code:
              type: string
            text:
              type: string
        success:
          type: boolean

    ErrorResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              type: object
              nullable: true

    PaginatedResponse:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
        total:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer

    

    StudentProfileResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/Student'

    ProfessorProfileResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/Professor'

    UpdateStudentRequest:
      type: object
      properties:
        study_group:
          type: string
        description:
          type: string
        github_alias:
          type: string
        tg_alias:
          type: string
        skills:
          type: array
          items:
            type: string
        roles:
          type: array
          items:
            type: string

    UpdateProfessorRequest:
      type: object
      properties:
        tg_alias:
          type: string
          nullable: true

    Studet:
      type: object
      properties:
        id:
          type: integer
        person_id:
          type: integer
        study_group:
          type: string
        description:
          type: string
          nullable: true
        github_alias:
          type: string
        tg_alias:
          type: string
        skills:
          type: array
          items:
            $ref: '#/components/schemas/Skill'
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'

    Professor:
      type: object
      properties:
        id:
          type: integer
        person_id:
          type: integer
        tg_alias:
          type: string
          nullable: true


    Skill:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true

    Role:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true


security:
  - bearerAuth: []

paths:
  /student/profile:
    get:
      tags: [Student]
      summary: Get student profile
      responses:
        '200':
          description: Student profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentProfileResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (user is not a student)

    put:
      tags: [Student]
      summary: Update student profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStudentRequest'
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentProfileResponse'
        '400':
          description: Invalid request
        '403':
          description: Forbidden

  /professor/profile:
    get:
      tags: [Professor]
      summary: Get professor profile
      responses:
        '200':
          description: Professor profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfessorProfileResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (user is not a professor)

    put:
      tags: [Professor]
      summary: Update professor profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfessorRequest'
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfessorProfileResponse'
        '400':
          description: Invalid request
        '403':
          description: Forbidden

  /profile/{person_id}/skills:
    get:
      tags: [Profile]
      summary: Get skills of a profile
      parameters:
        - in: path
          name: person_id
          required: true
          schema:
            type: integer
          description: Person id
      responses:
        '200':
          description: List of skills for the profile
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skill'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

    post:
      tags: [Profile]
      summary: Add a skill to a profile
      parameters:
        - in: path
          name: person_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                skill_id:
                  type: integer
              required:
                - skill_id
      responses:
        '200':
          description: Skill added
        '400':
          description: Invalid input
        '403':
          description: Forbidden

  /profile/{person_id}/{skill_id}:
    delete:
      tags: [Profile]
      summary: Remove a skill from a profile
      parameters:
        - in: path
          name: person_id
          required: true
          schema:
            type: integer
        - in: path
          name: skill_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Skill removed
        '404':
          description: Skill not found in profile
        '403':
          description: Forbidden


  /profile/{person_id}/roles:
    get:
      tags: [Profile]
      summary: Get roles of a profile
      parameters:
        - in: path
          name: person_id
          required: true
          schema:
            type: integer
          description: Person id
      responses:
        '200':
          description: List of roles for the profile
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      
    post:
      tags: [Profile]
      summary: Add a role to a profile
      parameters:
        - in: path
          name: person_id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role_id:
                  type: integer
              required:
                - role_id
      responses:
        '200':
          description: Role added
        '400':
          description: Invalid input
        '403':
          description: Forbidden
    
  /profile/{person_id}/{role_id}:
    delete:
      tags: [Profile]
      summary: Remove a role from a profile
      parameters:
        - in: path
          name: person_id
          required: true
          schema:
            type: integer
        - in: path
          name: role_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Role removed
        '404':
          description: Role not found in profile
        '403':
          description: Forbidden