name: Build TeamSync-Frontend Dev

on:
  push:
    branches:
      - '**'

jobs:
  build:
    permissions:
      contents: read
      packages: write
      pull-requests: write
    uses: ./.github/workflows/template-build-frontend.yml
    with:
      service-dir: back/frontend
      image-name: ts-frontend-dev
      backend-host: ${{ secrets.BACKEND_HOST_DEV }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
