name: Build TeamSync-Auth

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'
jobs:
  build:
    permissions:
      contents: read
      packages: write
      pull-requests: write
    uses: ./.github/workflows/template-build-backend.yml
    with:
      service-dir: back/auth
      image-name: ts-auth
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
