name: TeamSync-Auth Build

on:
  push:
    branches:
      - '**'

jobs:
  push:
    permissions:
      contents: read
      packages: write
      pull-requests: write
    uses: ./.github/workflows/build-template.yml
    with:
      service-dir: back/auth
      image-name: ts-auth
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
