# name: Deploy Production

# on:
#   push:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup SSH agent and add key
#         uses: webfactory/ssh-agent@v0.8.1
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy to server
#         run: |
#           ssh -o StrictHostKeyChecking=no githubci@shqcore.ru "cd  && ./deploy.sh"