name: Dev Deploy All

on:
  workflow_dispatch:

jobs:
  dev-deploy-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no githubci@team-sync.online "cd deploy/dev && bash ./deploy-all.sh ${{ github.ref_name }}"