name: Build Backend Template

on:
  workflow_call:
    inputs:
      service-dir:
        required: true
        type: string
      image-name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Determine tag
        id: tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            FINAL_TAG="${{ github.head_ref }}"
          else
            REF=${{ github.head_ref }}
            TAG=$(echo "$REF" | grep -oE 'TS-[0-9]+' | tr '[:upper:]' '[:lower:]')

            if [[ -n "$TAG" ]]; then
              if [[ "$REF" == "main" ]]; then
                FINAL_TAG="main-$TAG"
              else
                FINAL_TAG="$TAG"
              fi
            else
              FINAL_TAG="dev-$(date +%s)"
            fi
          fi

          echo "tag=$FINAL_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.service-dir }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image-name }}:${{ steps.tag.outputs.tag }}
