name: TeamSync-Resume Test And Push

on:
  push:
    branches:
      - '**'

jobs:
  test-push:
    permissions:
      contents: read
      packages: write
      pull-requests: write
    uses: ./.github/workflows/test-push-template.yml
    with:
      service-dir: back/resume
      test-report-title: Resume Service Test Coverage
      image-name: ts-resume
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
