name: Java Resume Service Test Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  call-template:
    uses: ./.github/workflows/templates/jacoco-report-template.yml
    with:
      service-dir: back/resume
      report-title: Resume Service Test Coverage
