name: Java Projects Service Test Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  call-template:
    uses: ./.github/workflows/templates/jacoco-report-template.yml
    with:
      service-dir: back/projects
      report-title: Projects Service Test Coverage
