name: TeamSync-Projects Test And Build

on:
  push:
    branches:
      - '**'

jobs:
  test-build:
    permissions:
      contents: read
      packages: write
      pull-requests: write
    uses: ./.github/workflows/test-build-template.yml
    with:
      service-dir: back/projects
      test-report-title: Projects Service Test Coverage
      image-name: ts-projects
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
