name: TeamSync-Projects Test And Push

on:
  push:
    branches:
      - '**'

jobs:
  test-push:
    permissions:
      contents: read
      packages: write
      pull-requests: write
    uses: ./.github/workflows/test-push-template.yml
    with:
      service-dir: back/projects
      test-report-title: Projects Service Test Coverage
      image-name: ts-projects

